version: '3'
services:
  tomcat:
    image: tomcat:jre17-temurin-noble
    ports:
      - "8081:8080"
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: mylibrary
    ports:
      - "3306:3306"

